# Generated by Django 5.2.17 on 2026-08-31 21:46

import chores.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('weekly_capacity_minutes', models.PositiveIntegerField(blank=True, help_text='Minutes of chores per week this person can take. Leave blank for an equal share of the total.', null=True)),
                ('feed_token', models.CharField(default=chores.models._make_feed_token, help_text="Unguessable slug used in this person's ICS feed URL.", max_length=64, unique=True)),
            ],
            options={
                'verbose_name_plural': 'people',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('effort_minutes', models.PositiveIntegerField(help_text='Estimated time to do this chore once. Drives fair-share balancing.')),
                ('interval_min_days', models.PositiveIntegerField(help_text='Minimum days between occurrences.')),
                ('interval_max_days', models.PositiveIntegerField(help_text='Maximum days between occurrences.')),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('anchor_date', models.DateField(help_text='Date this chore was last done (or should start counting from). The next occurrence is scheduled interval_min..max days after this.')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('interval_min_days__lte', models.F('interval_max_days'))), name='chore_interval_min_lte_max'), models.CheckConstraint(condition=models.Q(('interval_min_days__gte', 1)), name='chore_interval_min_at_least_1')],
            },
        ),
        migrations.CreateModel(
            name='FairnessLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_minutes', models.IntegerField(default=0, help_text='Running credit (negative) / debt (positive) carried between weeks so past imbalance is corrected going forward.')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='chores.person')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pinned', models.BooleanField(default=False, help_text='Pinned instances are kept as-is when the schedule is regenerated.')),
                ('uid', models.CharField(default=chores.models._make_instance_uid, max_length=100, unique=True)),
                ('sequence', models.PositiveIntegerField(default=0, help_text='Bumped whenever this instance changes, for ICS updates.')),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='chores.chore')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='chores.person')),
            ],
            options={
                'ordering': ['date', 'chore__name'],
                'indexes': [models.Index(fields=['person', 'date'], name='chores_sche_person__234c87_idx'), models.Index(fields=['chore', 'date'], name='chores_sche_chore_i_df2bbf_idx')],
            },
        ),
    ]
